---
title: "Untitled"
author: "MOEKA"
date: "2025-04-25"
output: html_document
---

```{r library, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggpmisc)

library(tidyr)
library(dplyr)
library(broom)
library(gridExtra)
library(stringr)
library(data.table)
library(forestmangr)
library(googlesheets4)
library(ggpubr)

library(rJava)
library(glmulti)
library(metafor)

library(purrr)
library(lme4)
library(patchwork)
library(stringr)

library(rlang)
```

```{r read dfs}
lit_effect <- read.csv("G:/My Drive/Research/Projects/SR_meta_analysis/Data/Ln_RR_raw.csv")

# Management type
CC <- lit_effect %>% filter(Management_type == "Clearcut")
PB <- lit_effect %>% filter(Management_type == "Prescribed burn")
TH <- lit_effect %>% filter(Management_type == "Thinning")
```

```{r common var}
# Define respiration components
Resp_Components <- c("ln_SR", "ln_Rh", "ln_Ra")

# season
season <- c(Spring = "Spring", Summer = "Summer", Fall = "Fall", Winter = "Winter")
levels(season) = c("Spring", "Summer", "Fall", "Winter")

# forest type
Forest <- c(Broadleaf = "Broadleaf", Needleleaf = "Needleleaf")

# leaf type
Leaf <- c(Deciduous = "Deciduous", Evergreen = "Evergreen", Mix = "Mixed") 

# residue
Residue_class <- c(Y = "Y", N = "N")

# time since
time_since_list <- c(Early = "Early", medium = "Medium", late = "Late")
```

```{r CC cat comparison}
###########
### Management
##############
CC_Resp_Mng <- list()

CC_sub <- CC %>% mutate(sub_mng = ifelse(is.na(Sub_management) == T, "N", "Y"))

CC_sub_mng <- c(Y = "Y", N = "N")

for (resp in Resp_Components) {
    for (var in names(CC_sub_mng)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_Resp_Mng[[group_name]] <- run_boot_lmer(
            CC_sub %>% filter(sub_mng == TH_sub_mng[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_Resp_Mng_results <- 
    bind_rows(CC_Resp_Mng, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Climate = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

write.csv(CC_Resp_Mng_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_sub_mng_result.csv", row.names = F)

CC_mng_SR <- aov(ln_SR ~ sub_mng, data = CC_sub)
summary(CC_mng_SR)

CC_mng_Rh <- aov(ln_Rh ~ sub_mng, data = CC_sub)
summary(CC_mng_Rh)

CC_mng_Ra <- aov(ln_Ra ~ sub_mng, data = CC_sub)
summary(CC_mng_Ra)

##############
# Severity
#############
CC_Resp_Severity <- list() 

# Define severity levels
CC_Severity <- c(Stem = "S", WT = "WT", WTS = "WTS", WTSC = "WTSC")

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(CC_Severity)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_Resp_Severity[[group_name]] <- run_boot_lmer(
            CC %>% filter(Severity_level == CC_Severity[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_Resp_Severity_results <- 
    bind_rows(CC_Resp_Severity, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Severity = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    )

#write.csv(CC_Resp_Severity_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_severity_result.csv", row.names = F)


CC_severity_SR <- aov(ln_SR ~ Severity_level, data = CC %>% filter(!Severity_level == "High" & !Severity_level == "NA"))
summary(CC_severity_SR) 
TukeyHSD(CC_severity_SR)


##########
# Season
##########
CC_Resp_Season <- list()

for (resp in Resp_Components) {
    for (var in names(season)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_Resp_Season[[group_name]] <- run_boot_lmer(
            CC %>% filter(Season == season[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_Resp_Season_results <- 
    bind_rows(CC_Resp_Season, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Season = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    )
#write.csv(CC_Resp_Season_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_Resp_Season_result.csv", row.names = F)

CC_season_SR <- aov(ln_SR ~ Season, data = CC %>% filter(Season != "NA"))
summary(CC_season_SR) 
TukeyHSD(CC_season_SR)

#########
# Forest type ##
########
CC_Resp_Forest <- list()

for (resp in Resp_Components) {
    for (var in names(Forest)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_Resp_Forest[[group_name]] <- run_boot_lmer(
            CC %>% filter(Forest_type == Forest[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_Resp_Forest_results <- 
    bind_rows(CC_Resp_Forest, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Forest = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(CC_Resp_Forest_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_Resp_Forest_result.csv", row.names = F)


# ANOVA
CC_forest_SR <- aov(ln_SR ~ Forest_type, data = CC)
summary(CC_forest_SR) 

CC_forest_Rh <- aov(ln_Rh ~ Forest_type, data = CC)
summary(CC_forest_Rh) 

CC_forest_Ra <- aov(ln_Ra ~ Forest_type, data = CC)
summary(CC_forest_Ra) 

#########
# Leaf ##
########
CC_Resp_Leaf <- list()

for (resp in Resp_Components) {
    for (var in names(Leaf)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_Resp_Leaf[[group_name]] <- run_boot_lmer(
            CC %>% filter(Leaf_habit == Leaf[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_Resp_Leaf_results <- 
    bind_rows(CC_Resp_Leaf, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Leaf = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(CC_Resp_Leaf_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_Resp_Leaf_result.csv", row.names = F)


# ANOVA
CC_Leaf_SR <- aov(ln_SR ~ Leaf_habit, data = CC)
summary(CC_Leaf_SR)
TukeyHSD(CC_Leaf_SR) 

CC_Leaf_Rh <- aov(ln_Rh ~ Leaf_habit, data = CC)
summary(CC_Leaf_Rh) 
TukeyHSD(CC_Leaf_Rh)

CC_Leaf_Ra <- aov(ln_Ra ~ Leaf_habit, data = CC)
summary(CC_Leaf_Ra) 
TukeyHSD(CC_Leaf_Ra)

###########
### Climate
##############
CC_Resp_Climate <- list()

# Define severity levels
CC_climate <- 
  c(Temperate = "Temperate", Mediterranean = "Mediterranean", Subtropical = "Subtropical",
    Boreal = "Boreal", Tropical = "Tropical")

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(CC_climate)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_Resp_Climate[[group_name]] <- run_boot_lmer(
            CC %>% filter(Climate_zone == CC_climate[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_Resp_Climate_results <- 
    bind_rows(CC_Resp_Climate, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Climate = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(CC_Resp_Climate_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_Climate_result.csv", row.names = F)

CC_Climate_SR <- aov(ln_SR ~ Climate_zone, data = CC)
summary(CC_Climate_SR)
TukeyHSD(CC_Climate_SR)

CC_Climate_Rh <- aov(ln_Rh ~ Climate_zone, data = CC)
summary(CC_Climate_Rh)

CC_Climate_Ra <- aov(ln_Ra ~ Climate_zone, data = CC)
summary(CC_Climate_Ra)
TukeyHSD(CC_Climate_Ra)

###########
### Residue
##############
CC_Resp_Residue <- list()

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(Residue_class)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_Resp_Residue[[group_name]] <- run_boot_lmer(
            CC %>% filter(Residue == Residue_class[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_Resp_Residue_results <- 
    bind_rows(CC_Resp_Residue, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Residue = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(CC_Resp_Residue_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_Residue_result.csv", row.names = F)

CC_Residue_SR <- aov(ln_SR ~ Residue, data = CC)
summary(CC_Residue_SR)
TukeyHSD(CC_Residue_SR)

CC_Residue_Rh <- aov(ln_Rh ~ Residue, data = CC)
summary(CC_Residue_Rh)

CC_Residue_Ra <- aov(ln_Ra ~ Residue, data = CC)
summary(CC_Residue_Ra)

######
# timing
########
CC_resp_Time <- list() 

CC_time <- CC %>% 
  mutate(Time_since_cat = 
           ifelse(Time_since <= 2, "Early", ifelse((Time_since > 2 & Time_since <= 5), "Medium", "Late")))

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(time_since_list)) {
        group_name <- paste("CC", resp, var, sep = "_")
        CC_resp_Time[[group_name]] <- run_boot_lmer(
            CC_time %>% filter(Time_since_cat == time_since_list[[var]]),
            resp
        )
    }
}

# Bind and process results
CC_resp_time_results <- 
  bind_rows(CC_resp_Time, .id = "Group") %>% 
  mutate(
    var = word(Group, 3, sep = "_"),
    Time = word(Group, -1, sep = "_")
  ) %>% 
  mutate(
    across(Intercept:Intercept_Upper, 
           ~ (exp(1)^(.) - 1) * 100,
           .names = "{.col}_pct_change")
  )

write.csv(CC_resp_time_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/CC_resp_time_result.csv", row.names = F)

CC_time_SR <- aov(ln_SR ~ Time_since_cat, data = CC_time)
summary(CC_time_SR)
TukeyHSD(CC_time_SR)

CC_time_Rh <- aov(ln_Rh ~ Time_since_cat, data = CC_time)
summary(CC_time_Rh)

CC_time_Ra <- aov(ln_Ra ~ Time_since_cat, data = CC_time)
summary(CC_time_Ra)
TukeyHSD(CC_time_Ra)
```

```{r TH cat comparison}
###########
### Management
##############
TH_Resp_Mng <- list()

TH_sub <- TH %>% mutate(sub_mng = ifelse(is.na(Sub_management) == T, "N", "Y"))

TH_sub_mng <- c(Y = "Y", N = "N")

for (resp in Resp_Components) {
    for (var in names(TH_sub_mng)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_Resp_Mng[[group_name]] <- run_boot_lmer(
            TH_sub %>% filter(sub_mng == TH_sub_mng[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_Resp_Mng_results <- 
    bind_rows(TH_Resp_Mng, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Climate = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

write.csv(TH_Resp_Mng_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_sub_mng_result.csv", row.names = F)

TH_mng_SR <- aov(ln_SR ~ sub_mng, data = TH_sub)
summary(TH_mng_SR)


###########
### Climate
##############
TH_Resp_Climate <- list()

# Define severity levels
TH_climate <- c(Temperate = "Temperate", Mediterranean = "Mediterranean", Subtropical = "Subtropical", Toropical = "Tropical")

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(TH_climate)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_Resp_Climate[[group_name]] <- run_boot_lmer(
            TH %>% filter(Climate_zone == TH_climate[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_Resp_Climate_results <- 
    bind_rows(TH_Resp_Climate, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Climate = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(TH_Resp_Climate_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_Climate_result.csv", row.names = F)

TH_Climate_SR <- aov(ln_SR ~ Climate_zone, data = TH)
summary(TH_Climate_SR)
TukeyHSD(TH_Climate_SR)

TH_Climate_Rh <- aov(ln_Rh ~ Climate_zone, data = TH)
summary(TH_Climate_Rh)

TH_Climate_Ra <- aov(ln_Ra ~ Climate_zone, data = TH)
summary(TH_Climate_Ra)
TukeyHSD(TH_Climate_Ra)

##########
# Season
##########
TH_Resp_Season <- list()

for (resp in Resp_Components) {
    for (var in names(season)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_Resp_Season[[group_name]] <- run_boot_lmer(
            TH %>% filter(Season == season[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_Resp_Season_results <- 
    bind_rows(TH_Resp_Season, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Season = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    )

#write.csv(TH_Resp_Season_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_Resp_Season_result.csv", row.names = F)

# ANOVA
TH_season_SR <- aov(ln_SR ~ Season, data = TH %>% filter(Season != "NA"))
summary(TH_season_SR) 

TH_season_Rh <- aov(ln_Rh ~ Season, data = TH %>% filter(Season != "NA"))
summary(TH_season_Rh) 
TukeyHSD(TH_season_Rh)

TH_season_Ra <- aov(ln_Ra ~ Season, data = TH %>% filter(Season != "NA"))
summary(TH_season_Ra) 
TukeyHSD(TH_season_Ra)

##########
# Severity
#########
TH_Resp_Severity <- list()

# Define severity levels
TH_Severity <- c(Low = "Low", Moderate = "Moderate", High = "High")
TH_Severity <- factor(TH_Severity, levels = c("Low", "Moderate", "High"))

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(TH_Severity)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_Resp_Severity[[group_name]] <- run_boot_lmer(
            TH %>% filter(Severity_level == TH_Severity[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_Resp_Severity_results <- 
    bind_rows(TH_Resp_Severity, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Severity = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(TH_Resp_Severity_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_severity_result.csv", row.names = F)

# ANOVA
TH_severity_SR <- aov(ln_SR ~ Severity_level, data = TH %>% filter(Severity_level != "NA"))
summary(TH_severity_SR) 

TH_severity_Rh <- aov(ln_Rh ~ Severity_level, data = TH %>% filter(Severity_level != "NA"))
summary(TH_severity_Rh) 

TH_severity_Ra <- aov(ln_Ra ~ Severity_level, data = TH %>% filter(Severity_level != "NA"))
summary(TH_severity_Ra) 
TukeyHSD(TH_severity_Ra)

#########
# Forest type ##
########
TH_Resp_Forest <- list()

for (resp in Resp_Components) {
    for (var in names(Forest)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_Resp_Forest[[group_name]] <- run_boot_lmer(
            TH %>% filter(Forest_type == Forest[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_Resp_Forest_results <- 
    bind_rows(TH_Resp_Forest, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Forest = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(TH_Resp_Forest_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_Resp_Forest_result.csv", row.names = F)

TH_forest_SR <- aov(ln_SR ~ Forest_type, data = TH)
summary(TH_forest_SR)
TukeyHSD(TH_forest_SR)

#########
# Leaf ##
########
TH_Resp_Leaf <- list()

TH_leaf <- c(Deciduous = "Deciduous", Evergreen = "Evergreen")

for (resp in Resp_Components) {
    for (var in names(TH_leaf)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_Resp_Leaf[[group_name]] <- run_boot_lmer(
            TH %>% filter(Leaf_habit == TH_leaf[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_Resp_Leaf_results <- 
    bind_rows(TH_Resp_Leaf, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Leaf = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(TH_Resp_Leaf_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_Resp_Leaf_result.csv", row.names = F)

TH_Leaf_SR <- aov(ln_SR ~ Leaf_habit, data = TH)
summary(TH_Leaf_SR) 


###########
### Residue
##############
TH_Resp_Residue <- list()

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(Residue_class)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_Resp_Residue[[group_name]] <- run_boot_lmer(
            TH %>% filter(Residue == Residue_class[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_Resp_Residue_results <- 
    bind_rows(TH_Resp_Residue, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Residue = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

#write.csv(TH_Resp_Residue_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_Residue_result.csv", row.names = F)

TH_Residue_SR <- aov(ln_SR ~ Residue, data = TH %>% filter(Residue != "NA"))
summary(TH_Residue_SR) 

# timing
TH_resp_Time <- list() 

TH_time <- TH %>% 
  mutate(Time_since_cat = 
           ifelse(Time_since <= 2, "Early", ifelse((Time_since > 2 & Time_since <= 5), "Medium", "Late")))

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(time_since_list)) {
        group_name <- paste("TH", resp, var, sep = "_")
        TH_resp_Time[[group_name]] <- run_boot_lmer(
            TH_time %>% filter(Time_since_cat == time_since_list[[var]]),
            resp
        )
    }
}

# Bind and process results
TH_resp_time_results <- 
  bind_rows(TH_resp_Time, .id = "Group") %>% 
  mutate(
    var = word(Group, 3, sep = "_"),
    Time = word(Group, -1, sep = "_")
  ) %>% 
  mutate(
    across(Intercept:Intercept_Upper, 
           ~ (exp(1)^(.) - 1) * 100,
           .names = "{.col}_pct_change")
  )

write.csv(TH_resp_time_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/TH_resp_time_result.csv", row.names = F)

TH_time_SR <- aov(ln_SR ~ Time_since_cat, data = TH_time)
summary(TH_time_SR)

TH_time_Rh <- aov(ln_Rh ~ Time_since_cat, data = TH_time)
summary(TH_time_Rh)

TH_time_Ra <- aov(ln_Ra ~ Time_since_cat, data = TH_time)
summary(TH_time_Ra)
```

```{r PB cat comparison}

##########
# Season
##########
PB_Resp_Season <- list()

for (resp in Resp_Components) {
    for (var in names(season)) {
        group_name <- paste("PB", resp, var, sep = "_")
        PB_Resp_Season[[group_name]] <- run_boot_lmer(
            PB %>% filter(Season == season[[var]]),
            resp
        )
    }
}

# Bind and process results
PB_Resp_Season_results <- 
    bind_rows(PB_Resp_Season, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Season = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    )

write.csv(PB_Resp_Season_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/PB_Resp_Season_result.csv", row.names = F)

PB_season_SR <- aov(ln_SR ~ Season, data = PB %>% filter(Season != "NA"))
summary(PB_season_SR) 

#########
# Forest type ##
########

PB_Resp_Forest <- list()

for (resp in Resp_Components) {
    for (var in names(Forest)) {
        group_name <- paste("PB", resp, var, sep = "_")
        PB_Resp_Forest[[group_name]] <- run_boot_lmer(
            PB %>% filter(Forest_type == Forest[[var]]),
            resp
        )
    }
}

# Bind and process results
PB_Resp_Forest_results <- 
    bind_rows(PB_Resp_Forest, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Forest = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

write.csv(PB_Resp_Forest_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/PB_Resp_Forest_result.csv", row.names = F)

# ANOVA
PB_forest_SR <- aov(ln_SR ~ Forest_type, data = PB)
summary(PB_forest_SR) 


###########
### Climate
##############
PB_Resp_Climate <- list()

# Define severity levels
PB_climate <- 
  c(Temperate = "Temperate", Mediterranean = "Mediterranean", Subtropical = "Subtropical",
    Boreal = "Boreal", Tropical = "Tropical")

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(PB_climate)) {
        group_name <- paste("PB", resp, var, sep = "_")
        PB_Resp_Climate[[group_name]] <- run_boot_lmer(
            PB %>% filter(Climate_zone == PB_climate[[var]]),
            resp
        )
    }
}

# Bind and process results
PB_Resp_Climate_results <- 
    bind_rows(PB_Resp_Climate, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Climate = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

write.csv(PB_Resp_Climate_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/PB_Climate_result.csv", row.names = F)


PB_Climate_SR <- aov(ln_SR ~ Climate_zone, data = PB)
summary(PB_Climate_SR)
TukeyHSD(PB_Climate_SR)


###########
### Repeat
##############
PB_Resp_Repeat <- list()

# Define severity levels
PB_Repeat <- c(Y = "Y", N = "N")

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(PB_Repeat)) {
        group_name <- paste("PB", resp, var, sep = "_")
        PB_Resp_Repeat[[group_name]] <- run_boot_lmer(
            PB %>% filter(Repeat == PB_Repeat[[var]]),
            resp
        )
    }
}

# Bind and process results
PB_Resp_Repeat_results <- 
    bind_rows(PB_Resp_Repeat, .id = "Group") %>% 
    mutate(
        Resp = word(Group, 3, sep = "_"),
        Repeat = word(Group, -1, sep = "_")
    ) %>% 
    mutate(
        across(Intercept:Intercept_Upper, 
               ~ (exp(1)^(.) - 1) * 100,
               .names = "{.col}_pct_change")
    ) %>% 
  mutate(Response = factor(Response, levels = c("ln_SR", "ln_Rh", "ln_Ra")))

write.csv(PB_Resp_Repeat_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/PB_Repeat_result.csv", row.names = F)

PB_Repeat_SR <- aov(ln_SR ~ Repeat, data = PB)
summary(PB_Repeat_SR)
TukeyHSD(PB_Repeat_SR)

# timing

PB_resp_Time <- list() 

PB_time <- PB %>% 
  mutate(Time_since_cat = 
           ifelse(Time_since <= 2, "Early", ifelse((Time_since > 2 & Time_since <= 5), "Medium", "Late")))

# Run boot_lmer for each component and severity level
for (resp in Resp_Components) {
    for (var in names(time_since_list)) {
        group_name <- paste("PB", resp, var, sep = "_")
        PB_resp_Time[[group_name]] <- run_boot_lmer(
            PB_time %>% filter(Time_since_cat == time_since_list[[var]]),
            resp
        )
    }
}

# Bind and process results
PB_resp_time_results <- 
  bind_rows(PB_resp_Time, .id = "Group") %>% 
  mutate(
    var = word(Group, 3, sep = "_"),
    Time = word(Group, -1, sep = "_")
  ) %>% 
  mutate(
    across(Intercept:Intercept_Upper, 
           ~ (exp(1)^(.) - 1) * 100,
           .names = "{.col}_pct_change")
  )

write.csv(PB_resp_time_results, "G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_ind/PB_resp_time_result.csv", row.names = F)

PB_time_SR <- aov(ln_SR ~ Time_since_cat, data = PB_time)
summary(PB_time_SR)
```

```{r read summary df}
cat_summary <- read.csv("G:/My Drive/Research/Projects/SR_meta_analysis/Data/cat_summary.csv")

plot_cat_summary <- 
   cat_summary %>%
   filter(n_study > 1) %>%
   mutate(
     color_group = case_when(
     Intercept_Lower_pct_change > 0 & Intercept_Upper_pct_change > 0 ~ "royalblue",
     Intercept_Lower_pct_change < 0 & Intercept_Upper_pct_change < 0 ~ "red2",
     TRUE ~ "black")
 )
```


```{r graph function}
cat_graph <- function(df, title, xval){
  df$Var_kind <- factor(df$Var_kind, levels = rev(unique(df$Var_kind)))  # preserve order in df
  ggplot(df) +
    geom_point(aes(
      x = Intercept_pct_change,
      y = Var_kind,
      color = color_group
    ), size = 5) +
    geom_errorbarh(aes(
        y = Var_kind,
        xmin = Intercept_Lower_pct_change,
        xmax = Intercept_Upper_pct_change,
        color = color_group), 
      height = 0.2, linewidth = 1.5) +
    geom_vline(xintercept = 0, color = "black", size = 1, alpha = 0.4) +
    geom_text(aes(
      x = Intercept_Upper_pct_change + 25,
      y = Var_kind,
      label = paste0(n_obs, " (", n_study, ")")
      ),
      vjust = 0.5, size = 5) +
    geom_text(aes(
      x = Intercept_Upper_pct_change + 7,
      y = Var_kind,
      label = significant
      ),
      vjust = 0.5, size = 5) +
    scale_color_identity(guide = "none") + 
    xlab("") +
    ggtitle(title) +
    theme_classic2() +
    xlim(-1 * xval, xval) +
    theme(
      axis.title.x = element_text(size = 18),
      axis.text.x = element_text(size = 18),
      axis.title.y = element_blank(),
      axis.text.y = element_text(size = 18),
      strip.text = element_text(size = 18),
      #panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.1),
      plot.title = element_text(size = 19, face = "bold")
    )
}
```

```{r SR plot}
#CC_SR
p1 <- 
  plot_cat_summary %>%
  filter(Management == "Clearcut", Resp == "SR") %>%
  filter(!Var %in% c("Leaf_type", "Season")) %>% 
  cat_graph(title = "Clearcut", 75) 

#TH_SR
p2 <- 
  plot_cat_summary %>%
  filter(Management == "Thinning", Resp == "SR") %>%
  filter(!Var %in% c("Leaf_type", "Season")) %>% 
  cat_graph(title = "Thinning", 75)

#PB_SR
p3 <- 
  plot_cat_summary %>%
  filter(Management == "Prescribed burn", Resp == "SR") %>%
  filter(!Var %in% c("Leaf_type", "Season")) %>%
  cat_graph(title = "Prescribed burn", 75)

library(patchwork)
p1 + p2 + p3
```

```{r comp plot}
#CC_Rh
p4 <- 
  plot_cat_summary %>%
  filter(Management == "Clearcut", Resp == "Rh") %>%
  filter(Var %in% c("Forest_type", "Recovery")) %>%
  cat_graph(title = "Clearcut", 65) 

#CC_Ra
p5 <- 
  plot_cat_summary %>%
  filter(Management == "Clearcut", Resp == "Ra") %>%
  filter(Var %in% c("Forest_type", "Recovery")) %>%
  cat_graph(title = "Clearcut", 100) 


#TH_Rh
p6 <- 
  plot_cat_summary %>%
  filter(Management == "Thinning", Resp == "Rh") %>%
  filter(Var %in% c("Severity","Recovery")) %>% 
  cat_graph(title = "Thinning", 65) 

# TH_Ra
p7 <- 
  plot_cat_summary %>%
  filter(Management == "Thinning", Resp == "Ra") %>%
  filter(Var %in% c("Severity","Recovery")) %>% 
  cat_graph(title = "Thinning", 100) 



# Rh
(p4 + p6) 
#Ra
(p5 + p7)
```